import Head from "next/head";
import { Button } from "@moai/core";
export default function Home() {
  return (
    <div className="sm:container mx-auto bg-gray-300 min-h-screen flex items-center justify-center">
      <Head>
        <title>Jump start</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button>Hello</Button>
    </div>
  );
}
